#!/usr/bin/env swift

// 脚本来添加中文翻译到Localizable.xcstrings
import Foundation

// 定义需要添加中文翻译的条目
let translations: [String: String] = [
    // 基础配置项
    "hostName": "图床名称",
    "region": "区域",
    "endpoint": "服务端 URL",
    "bucket": "空间名称",
    "operatorName": "操作员",
    "password": "密码",
    "accessKey": "Access Key",
    "secretId": "Secret Id",
    "secretKey": "Secret Key",
    "domain": "域名",
    "url": "API 地址",
    "method": "请求方式",
    "field": "文件字段名",
    "bodys": "请求体",
    "headers": "请求头",
    "owner": "用户名",
    "repo": "仓库名",
    "branch": "分支",
    "version": "版本",
    "token": "Token",
    "username": "用户名",
    "cookieMode": "Cookie 模式",
    "cookie": "Cookie",
    "quality": "图片质量",
    "otherFields": "其他字段",
    "headerData": "Headers 数据",
    "bodyData": "Body 数据",
    "clientId": "Client ID",
    "saveKeyPath": "保存路径",
    "useCdn": "使用默认 CDN",
    "suffix": "网址后缀",
    "resultPath": "结果路径",
    "useBase64": "使用 Base64",
    "customize": "自定义",

    // Host类型
    "SMMS": "SMMS",
    "Qiniu KODO": "七牛云 KODO",
    "Upyun USS": "又拍云 USS",
    "Aliyun OSS": "阿里云 OSS",
    "Tencent Cloud COS": "腾讯云 COS",
    "GitHub": "GitHub",
    "Gitee": "码云 Gitee",
    "Amazon S3 Compatible": "Amazon S3(S3协议)",
    "Imgur": "Imgur",
    "Baidu Cloud BOS": "百度云 BOS",

    // 微博质量
    "Thumbnail": "缩略图",
    "Medium": "中等大小",
    "Original": "原图",

    // Region - Aliyun OSS
    "East China 1 (Hangzhou)": "华东1（杭州）",
    "East China 2 (Shanghai)": "华东2（上海）",
    "East China 5 (Nanjing)": "华东5（南京-本地地域）",
    "East China 6 (Fuzhou)": "华东6（福州-本地地域）",
    "Central China 1 (Wuhan)": "华中1（武汉-本地地域）",
    "North China 1 (Qingdao)": "华北1（青岛）",
    "North China 2 (Beijing)": "华北2（北京）",
    "North China 3 (Zhangjiakou)": "华北3（张家口）",
    "North China 5 (Hohhot)": "华北5（呼和浩特）",
    "North China 6 (Wulancha)": "华北6（乌兰察布）",
    "South China 1 (Shenzhen)": "华南1（深圳）",
    "South China 2 (Heyuan)": "华南2（河源）",
    "South China 3 (Guangzhou)": "华南3（广州）",
    "Southwest 1 (Chengdu)": "西南1（成都）",
    "China (Hong Kong)": "中国（香港）",
    "Japan (Tokyo)": "日本（东京）",
    "Korea (Seoul)": "韩国（首尔）",
    "Singapore": "新加坡",
    "Malaysia (Kuala Lumpur)": "马来西亚（吉隆坡）",
    "Indonesia (Jakarta)": "印度尼西亚（雅加达）",
    "Philippines (Manila)": "菲律宾（马尼拉）",
    "Thailand (Bangkok)": "泰国（曼谷）",
    "Germany (Frankfurt)": "德国（法兰克福）",
    "London, (England)": "英国（伦敦）",
    "USA (Silicon Valley)": "美国（硅谷）",
    "USA (Virginia)": "美国（弗吉尼亚）",
    "United Arab Emirates (Dubai)": "阿联酋（迪拜）",
    "Mexico": "墨西哥",
    "No geographical attributes (Mainland China)": "无地域属性（中国内地）",

    // Region - Amazon S3
    "US East (Ohio)": "美国东部（俄亥俄州）",
    "US East (N. Virginia)": "美国东部（弗吉尼亚北部）",
    "US West (N. California)": "美国西部（加利福尼亚北部）",
    "US West (Oregon)": "美国西部（俄勒冈）",
    "Asia Pacific (Hong Kong)": "亚太地区（香港）",
    "Asia Pacific (Hyderabad)": "亚太地区（海得拉巴）",
    "Asia Pacific (Jakarta)": "亚太地区（雅加达）",
    "Asia Pacific (Malaysia)": "亚太地区（马来西亚）",
    "Asia Pacific (Melbourne)": "亚太地区（墨尔本）",
    "Asia Pacific (Mumbai)": "亚太地区（孟买）",
    "Asia Pacific (Osaka)": "亚太区域 (大阪)",
    "Asia Pacific (Seoul)": "亚太区域（首尔）",
    "Asia Pacific (Singapore)": "亚太区域（新加坡）",
    "Asia Pacific (Sydney)": "亚太区域（悉尼）",
    "Asia Pacific (Thailand)": "亚太区域（泰国）",
    "Asia Pacific (Tokyo)": "亚太区域（东京）",
    "Canada (Central)": "加拿大（中部）",
    "Canada West (Calgary)": "加拿大西部（卡尔加里）",
    "Europe (Frankfurt)": "欧洲（法兰克福）",
    "Europe (Ireland)": "欧洲（爱尔兰）",
    "Europe (London)": "欧洲（伦敦）",
    "Europe (Milan)": "欧洲（米兰）",
    "Europe (Paris)": "欧洲 (巴黎)",
    "Europe (Spain)": "欧洲（西班牙）",
    "Europe (Stockholm)": "欧洲（斯德哥尔摩）",
    "Europe (Zurich)": "欧洲（苏黎世）",
    "Israel (Tel Aviv)": "以色列（特拉维夫）",
    "Mexico (Central)": "墨西哥（中部）",
    "Middle East (Bahrain)": "中东（巴林）",
    "Middle East (UAE)": "中东（阿联酋）",
    "South America (São Paulo)": "南美洲（圣保罗）",
    "AWS GovCloud (US-East)": "AWS GovCloud (US-East)",
    "AWS GovCloud (US-West)": "AWS GovCloud (US-West)",
    "Africa (Cape Town)": "非洲（开普敦）",

    // Region - Baidu BOS
    "North China-Beijing": "华北-北京",
    "North China-Baoding": "华北-保定",
    "East China-Suzhou": "华东-苏州",
    "South China-Guangzhou": "华南-广州",
    "Southwest China-Chengdu": "西南-成都",
    "China Hong Kong": "中国香港",
    "Central China-Wuhan": "华中-武汉",
    "East China Finance-Shanghai": "华东金融-上海",

    // Region - Qiniu KODO
    "East China": "华东",
    "East China - Zhejiang 2": "华东-浙江2",
    "North China": "华北",
    "South China": "华南",
    "Northwest China - Shaanxi 1": "西北-陕西1",
    "North America": "北美",
    "Asia Pacific - Singapore": "亚太-新加坡",
    "Asia Pacific - Hanoi": "亚太-河内",
    "Asia Pacific - Ho Chi Minh": "亚太-胡志明",

    // Region - Tencent COS
    "Beijing First District": "北京一区",
    "Beijing": "北京",
    "Nanjing": "南京",
    "Shanghai (East China)": "上海",
    "Guangzhou (South China)": "广州",
    "Chengdu (Southwest)": "成都",
    "Chongqing": "重庆",
    "Shenzhen Finance": "深圳金融",
    "Shanghai Finance": "上海金融",
    "Beijing Finance": "北京金融",
    "Hong Kong, China": "中国香港",
    "Jakarta": "雅加达",
    "Seoul": "首尔",
    "Bangkok": "曼谷",
    "Tokyo": "东京",
    "Silicon Valley": "硅谷（美西）",
    "Virginia": "弗吉尼亚（美东）",
    "Sao Paulo": "圣保罗",
    "Frankfurt": "法兰克福",

    // 错误信息
    "Invalid signature": "无效的签名。",
    "Invalid config": "无效的配置。",
    "Invalid response": "无效的返回信息。",
    "Unknown host type": "未知的图床类型。",
    "File format not supported": "文件类型不支持。",
    "File is over the size limit! Limit:": "文件大小超过限制! 最大为:",
    "Unknown Error": "未知错误。"
]

print("翻译脚本已准备完成，包含 \(translations.count) 个翻译条目")
print("请手动将这些翻译添加到 Localizable.xcstrings 文件中")